version: '3'
services:
    
    dash-app:
        build:
            context: .
            dockerfile: dashboard/Dockerfile_dashboard  # Specify the unique Dockerfile name
        ports:
            - 8050:8050
        volumes:
            - ./dashboard:/app
            - ./data:/data
        environment:
            - DEBUG=True
            - NAME=Dash-App
            - PYTHONPATH=/app
        working_dir: /app
        depends_on:
            dashboard:
                condition: service_healthy
    
    data-retrieval:
        build:
            context: .
            dockerfile: notebook/Dockerfile_notebook
        ports:
            - 8888:8888
        volumes:
            - ./notebook:/notebook
            - ./data:/data
        working_dir: /notebook
    
    dashboard:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=student
            - POSTGRES_PASSWORD=infomdss
            - POSTGRES_DB=dashboard
        volumes:
            - dashboard-data:/var/lib/postgresql/data/
        container_name: dashboard
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
            interval: 3s
            timeout: 60s
            retries: 10
            start_period: 80s

volumes:
    dashboard-data:
